{% set name = "similaritymeasures" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/similaritymeasures-{{ version }}.tar.gz
  sha256: c08f6ea0b7bf233787c3db81ec392470aa9aa0248e07097d4b2cccb94f6d7055

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.14.0
    - python >=3.6
    - scipy >=0.19.0

test:
  imports:
    - similaritymeasures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cjekel/similarity_measures
  summary: Quantify the difference between two arbitrary curves in space
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/cjekel/similarity_measures
  doc_url: https://jekel.me/similarity_measures/index.html

extra:
  recipe-maintainers:
    - melonhead901
