{% set name = "similaritymeasures" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/similaritymeasures-{{ version }}.tar.gz
  sha256: 3734e8d2d0fbffbc288e94886fa7c19421ed8a7b7c12b52dc3556b75bebe0a8d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - numpy >=1.14.0
    - python >=3.6
    - scipy >=0.19.0

test:
  imports:
    - similaritymeasures
  commands:
    - pip check
  requires:
    - pip
    - setuptools

about:
  home: https://github.com/cjekel/similarity_measures
  summary: Quantify the difference between two arbitrary curves in space
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/cjekel/similarity_measures
  doc_url: https://jekel.me/similarity_measures/index.html

extra:
  recipe-maintainers:
    - melonhead901
